version: "3.8"

services:
  web-ui:
    container_name: web-ui
    image: "nginx:1.25.3-alpine-slim"
    ports:
      - "80:80"
    networks:
      - default
      - internal-services
    volumes:
      - ./web-ui/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./web-ui/static:/usr/share/nginx/html:ro
      - shared_data:/mnt/shared_data

  device-api:
    container_name: device-api
    image: "device-api:latest"
    ports:
      - 8080:8080
    networks:
      - internal-services
    volumes:
      - shared_data:/mnt/shared_data
    environment:
      API_USER: realuser
      API_TOKEN: 54321

networks:
  default:

  internal-services:
    driver: bridge

volumes:
  shared_data:
    name: shared_data
