version: "3.8"

services:
  web-ui:
    image: "nginx:1.25.3-alpine-slim"
    ports:
      - "80:80"
    networks:
      - default
      - internal-services
    volumes:
      - ./web-ui/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./web-ui/static:/usr/share/nginx/html:ro

  device-api:
    image: "device-api:latest"
    ports:
      - 8080:8080
    networks:
      - internal-services
    environment:
      API_USER: realuser
      API_TOKEN: 54321

networks:
  default:

  internal-services:
    driver: bridge
